apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app2
  name: application2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  strategy: {}
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - image: nginx
        name: nginx
