apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
      name: prometheus
    spec:
      containers:
        - args:
            - --web.enable-lifecycle
            - --web.config.file=/etc/prometheus1/web-config.yml
            - --config.file=/etc/prometheus2/prometheus.yml
          image: prom/prometheus:latest
          imagePullPolicy: IfNotPresent
          name: prometheus
          ports:
            - containerPort: 9090
              name: web
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/prometheus2
              name: config-volume
            - mountPath: /etc/prometheus-rules
              name: alertrules-volume
            - mountPath: /etc/prometheus1
              name: config-volume-2
            - mountPath: /etc/cert
              name: config-volume-3
            - mountPath: /etc/key
              name: config-volume-4
      serviceAccount: prometheus
      serviceAccountName: prometheus
      volumes:
        - configMap:
            defaultMode: 420
            name: config-volume-crt
          name: config-volume-3
        - configMap:
            defaultMode: 420
            name: config-volume-key
          name: config-volume-4
        - configMap:
            defaultMode: 420
            name: prometheus-configmap-web
          name: config-volume-2
        - configMap:
            defaultMode: 420
            name: prometheus-configmap
          name: config-volume
        - configMap:
            defaultMode: 420
            name: prometheus-alertrules
          name: alertrules-volume
