apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloservice
  namespace: monitoring 
spec:
  selector:
    matchLabels:
      app: helloservice
  replicas: 1
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: aloisreitbauer/hello-server:v0.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: PORT
          value: "9000"
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 15
